### ISSUE TITLE
Configure Directus for Different Environments

### ISSUE THREAD

**Issue by binaryben** [directus-labs/guest-authoring#93]
### What is your idea?

I'm noticing a few users are struggling with setting up environment variables properly and also with running in different environments (development, staging, production). Since it's something I'm establishing best practices for myself right now, I'd like to write a post that is a more hands on walk through of setting up dynamic environment variables when running in docker.

I'll assume readers know how to set up environment variables in `docker-compose.yml` as that is well covered in docs. One of my motives is to avoid users just resorting to storing everything in docker-compose config since they know how to and then committing it to git. I will also have to assume the reader has experience working within Node packages for sake of keeping to the point of the blog post.

Basic structure of post:

* Set up a multi environment project with Node
  * `npm dev` and `npm start` will run different config
* How to move env config to an external config file and load it as a volume
* Touch on secret management options without going into too many details (mainly links to relevant options)
  * I will probably use the `_FILE` option for the tutorial to keep it simple and mount a `directus/secrets` volume that is in `.gitignore`
  * Explain importance of not committing secrets in their .env files to git
* Provide a tutorial on how to set up a TypeScript file as the config to change settings based on environment
  * Automatically generate secret when in a development environment as an example
  * Use SQLite in development and Postgres in production
* Set up HTTPS with a local domain (https://directus.local) in a developer environment and change the PUBLIC_URL based on the environment
  * This can be very important when working with external services that need to be accessed via HTTPS even when developing

### What are the key takeaways from your post?

By the end of the tutorial, the reader should have a Directus project with a base `docker-compose.yml` file that looks something like this:

```yaml
version: "3"
services:
  directus:
    image: directus/directus:10.9.0
    ports:
      - 8055:8055
    volumes:
      - ./config:/directus/config
      # ./.local is in .gitignore
      - ./.local/volumes/uploads:/directus/uploads
      - ./.local/volumes/secrets:/directus/secrets
    environment:
      CONFIG_PATH: "/directus/config/directus.config.js" # Compiled from TypeScript
      # Note there is no other config here! 🎉 So clean...
  caddy:
    # ...
```

They will have at least two other docker-compose files that extends the base one. The first to add development changes. This will include a database volume, `NODE_ENV: development` and config for caddy to find the local certs. The second is to add postgres config.

Key takeaways:

* Environment management knowledge
* Three examples of using dynamically generated config in different environments (SQLite v Postgres, automatically generate secrets in dev, and different URLs)
* Extending Docker Compose files
* Better understanding of best practices around secret management

### What type of post is this?

Other

### Country of residence

Straya! 🇦🇺

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.
